/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface PasswordInputProps {
  label: string;
}

const PasswordInput: React.FC<PasswordInputProps> = ({ label }) => {
  return (
    <>
      <label
        htmlFor={`${label.toLowerCase().replace(" ", "-")}-input`}
        className="mt-6 text-base text-neutral-800"
      >
        {label}
      </label>
      <input
        type="password"
        id={`${label.toLowerCase().replace(" ", "-")}-input`}
        className="px-5 py-4 mt-3 max-w-full text-base whitespace-nowrap bg-white rounded-2xl border border-solid border-slate-200 text-slate-400 w-[510px]"
        placeholder="**********"
      />
    </>
  );
};

export default PasswordInput;
