/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ToggleSwitch from "./ToggleSwitch";
import PasswordInput from "./PasswordInput";
import SaveButton from "./SaveButton";

const SecuritySettings: React.FC = () => {
  return (
    <main className="flex flex-col rounded-none">
      <section className="flex flex-col py-9 w-full bg-white rounded-3xl max-md:max-w-full">
        <div className="flex flex-col items-start px-8 w-full max-md:px-5 max-md:max-w-full">
          <nav className="flex z-10 gap-5 justify-between ml-4 max-w-full text-base font-medium w-[239px] max-md:ml-2.5">
            <a href="#" className="self-start text-slate-400">
              Edit Profile
            </a>
            <div className="flex flex-col text-blue-700 whitespace-nowrap">
              <span className="self-center">Security</span>
              <div className="flex shrink-0 mt-2 bg-blue-700 rounded-xl h-[3px]" />
            </div>
          </nav>
          <hr className="flex shrink-0 self-stretch h-px bg-gray-100 max-md:max-w-full" />
          <h2 className="mt-9 text-lg font-medium text-slate-700">
            Two-factor Authentication
          </h2>
          <ToggleSwitch label="Enable or disable two factor authentication" />
          <h2 className="mt-7 text-lg font-medium text-slate-700">
            Change Password
          </h2>
          <PasswordInput label="Current Password" />
          <PasswordInput label="New Password" />
          <SaveButton />
        </div>
      </section>
    </main>
  );
};

export default SecuritySettings;
