/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ToggleSwitchProps {
  label: string;
}

const ToggleSwitch: React.FC<ToggleSwitchProps> = ({ label }) => {
  return (
    <div className="flex gap-5 mt-5 max-w-full w-[401px]">
      <label className="flex items-center cursor-pointer">
        <div className="relative">
          <input type="checkbox" className="sr-only" />
          <div className="flex flex-col justify-center items-start px-3 py-0.5 bg-teal-400 rounded-3xl w-14 h-7">
            <div className="flex shrink-0 bg-white rounded-full h-[27px] shadow-[0px_2px_5px_rgba(0,0,0,0.1)] w-[27px]" />
          </div>
        </div>
        <span className="flex-auto ml-5 my-auto text-base text-neutral-800 w-[314px]">
          {label}
        </span>
      </label>
    </div>
  );
};

export default ToggleSwitch;
