/**
 * This code was generated by Builder.io.
 */
import React from "react";

type ProfileImageProps = {
  src: string;
  alt: string;
};

const ProfileImage: React.FC<ProfileImageProps> = ({ src, alt }) => {
  return (
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className="object-contain shrink-0 self-start max-w-full aspect-[1.02] w-[132px]"
    />
  );
};

export default ProfileImage;
