/**
 * This code was generated by Builder.io.
 */
import React from "react";
import InputField from "./InputField";
import SelectField from "./SelectField";
import SaveButton from "./SaveButton";
import { Avatar, AvatarFallback, AvatarImage } from "../ui/avatar";

type ProfileEditorProps = {
  name: string;
  username: string;
  email: string;
  dateOfBirth: string;
  permanentAddress: string;
  presentAddress: string;
  city: string;
  postalCode: string;
  country: string;
};

const ProfileEditor: React.FC<ProfileEditorProps> = ({
  name,
  username,
  email,
  dateOfBirth,
  permanentAddress,
  presentAddress,
  city,
  postalCode,
  country,
}) => {
  return (
    <main className="flex flex-col rounded-none">
      <section className="flex flex-col px-8 py-9 w-full bg-white rounded-3xl max-md:px-5 max-md:max-w-full">
        <nav className="flex text-base font-medium max-md:max-w-full">
          <div className="flex flex-col text-blue-700">
            <div className="self-center">Edit Profile</div>
            <div className="flex shrink-0 mt-2 bg-blue-700 rounded-xl h-[3px]" />
          </div>
          <div className="flex flex-col grow shrink-0 whitespace-nowrap basis-0 text-slate-400 w-fit max-md:max-w-full">
            <div className="self-start ml-48 max-md:ml-2.5">Security</div>
            <div className="flex shrink-0 mt-2.5 h-px bg-gray-100 max-md:max-w-full" />
          </div>
        </nav>
        <div className="flex flex-wrap gap-10 mt-14 max-md:mt-10 max-md:max-w-full">
          <Avatar>
            <AvatarImage src="" />
            <AvatarFallback>NA</AvatarFallback>
          </Avatar>
          <form className="flex flex-col grow shrink-0 basis-0 w-fit max-md:max-w-full">
            <div className="flex flex-wrap gap-5 justify-between max-w-full text-base text-neutral-800 w-[532px]">
              <InputField label="Your Name" value={name} />
              <InputField label="User Name" value={username} />
            </div>
            <InputField label="Email" value={email} type="email" />
            <InputField label="Password" value="**********" type="password" />
            <SelectField label="Date of Birth" value={dateOfBirth} />
            <InputField label="Permanent Address" value={permanentAddress} />
            <InputField label="Present Address" value={presentAddress} />
            <InputField label="City" value={city} />
            <InputField label="Postal Code" value={postalCode} />
            <InputField label="Country" value={country} />
            <SaveButton />
          </form>
        </div>
      </section>
    </main>
  );
};

export default ProfileEditor;
