/**
 * This code was generated by Builder.io.
 */
import React from "react";

const BalanceHistory: React.FC = () => {
  return (
    <section className="w-full">
      <h2 className="mt-7 text-2xl font-semibold text-slate-700">
        Balance History
      </h2>
    </section>
  );
};

export default BalanceHistory;
