/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Sidebar from "./Sidebar";
import MainContent from "./MainContent";

const Dashboard: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <hr className="flex shrink-0 self-end max-w-full h-px bg-slate-200 w-[1190px]" />
      <div className="flex flex-wrap gap-10 w-full max-md:max-w-full">
        <Sidebar />
        <MainContent />
      </div>
    </div>
  );
};

export default Dashboard;
