/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ExpenseStatistics: React.FC = () => {
  return (
    <section className="flex flex-col text-2xl font-semibold text-slate-700">
      <h2 className="self-start mt-6">Expense Statistics</h2>
    </section>
  );
};

export default ExpenseStatistics;
