/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "../ui/avatar";
import { MdOutlineNotifications, MdOutlineSettings } from "react-icons/md";

const Header: React.FC = () => {
  return (
    <header className="flex flex-wrap gap-5 justify-between items-center px-10 py-5 w-full bg-white max-md:px-5 max-md:max-w-full">
      <div className="flex gap-10 my-auto items-center whitespace-nowrap text-yellow-950">
        <div className="flex gap-0.5 text-2xl ">
          <Image
            src="/android-icon-72x72.png"
            alt="logo"
            width={72}
            height={72}
            layout="responsive"
          />
        </div>
        <h1 className="scroll-m-20 text-2xl font-semibold tracking-tight ">
          Overview
        </h1>
      </div>
      <nav className="flex gap-8 items-center">
        <Link href="/dashboard/settings">
          <MdOutlineSettings size={24} color="#422006" />
        </Link>
        <Link href="/">
          <MdOutlineNotifications size={24} color="#422006" />
        </Link>
        <Link href="/">
          <Avatar>
            <AvatarImage src="" />
            <AvatarFallback>NA</AvatarFallback>
          </Avatar>
        </Link>
      </nav>
    </header>
  );
};

export default Header;
