/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MyCards from "./MyCards";
import WeeklyActivity from "./WeeklyActivity";
import BalanceHistory from "./BalanceHistory";
import RecentTransaction from "./RecentTransaction";
import ExpenseStatistics from "./ExpenseStatistics";

const MainContent: React.FC = () => {
  return (
    <main className="flex-auto px-10 py-6 bg-slate-100 max-md:px-5 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-[68%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col items-start w-full max-md:mt-10 max-md:max-w-full">
            <div className="self-stretch max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col">
                <MyCards />
                <WeeklyActivity />
              </div>
            </div>
            <BalanceHistory />
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[32%] max-md:ml-0 max-md:w-full">
          <RecentTransaction />
          <ExpenseStatistics />
        </div>
      </div>
    </main>
  );
};

export default MainContent;
