/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MyCards: React.FC = () => {
  return (
    <section className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow text-2xl font-semibold text-slate-700 max-md:mt-8">
        <h2 className="self-start">My Cards</h2>
      </div>
    </section>
  );
};

export default MyCards;
