/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Pagination: React.FC = () => {
  return (
    <nav
      className="flex gap-3 items-center self-end mt-8 text-base font-medium whitespace-nowrap rounded-none"
      aria-label="Pagination"
    >
      <button className="flex gap-1.5 self-stretch my-auto text-blue-700">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/34eb2d18a3afc8ee6c8dd97db17fb0cba2b084afe32e6a22958a465a2f00e930?placeholderIfAbsent=true&apiKey=65c59f804f0842d29a4e67cb1a2841cf"
          alt=""
          className="object-contain shrink-0 my-auto aspect-[0.5] w-[7px]"
        />
        <span>Previous</span>
      </button>
      <div className="flex gap-3 self-stretch">
        <button
          className="px-4 w-10 h-10 text-white bg-blue-700 rounded-xl"
          aria-current="page"
        >
          1
        </button>
        <button className="my-auto text-blue-700">2</button>
      </div>
      <button className="self-stretch my-auto text-blue-700">3</button>
      <button className="self-stretch my-auto text-blue-700">4</button>
      <button className="flex gap-1.5 self-stretch my-auto text-blue-700">
        <span>Next</span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2b2c1b67cb1591121a67994d79a31097bebae4c3587938971854b389a50d5b31?placeholderIfAbsent=true&apiKey=65c59f804f0842d29a4e67cb1a2841cf"
          alt=""
          className="object-contain shrink-0 my-auto aspect-[0.5] w-[7px]"
        />
      </button>
    </nav>
  );
};

export default Pagination;
