/**
 * This code was generated by Builder.io.
 */
import React from "react";

const RecentTransaction: React.FC = () => {
  return (
    <section className="flex flex-col text-2xl font-semibold text-slate-700 max-md:mt-10">
      <h2 className="self-start">Recent Transaction</h2>
      
    </section>
  );
};

export default RecentTransaction;
