/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TransactionRowProps {
  description: string;
  transactionId: string;
  type: "credit" | "debit";
  timestamp: string;
  amount: number;
  amountColor: string;
}

const TransactionRow: React.FC<TransactionRowProps> = ({
  description,
  transactionId,
  type,
  timestamp,
  amount,
  amountColor,
}) => {
  return (
    <div className="flex flex-wrap gap-8 mt-4">
      <div className="flex gap-3.5 my-auto">
        <div className="my-auto basis-auto">{description}</div>
      </div>
      <div className="flex flex-wrap flex-auto gap-10 items-center max-md:max-w-full">
        <div className="grow self-stretch my-auto">{transactionId}</div>
        <div className="self-stretch my-auto">{type}</div>
        <div className="self-stretch my-auto basis-auto">{timestamp}</div>
        <div className={`self-stretch my-auto font-medium ${amountColor}`}>
          {amount}
        </div>
        <button className="self-stretch px-4 py-2.5 text-base text-blue-900 whitespace-nowrap border border-blue-900 border-solid rounded-[50px]">
          Download
        </button>
      </div>
    </div>
  );
};

export default TransactionRow;
