/**
 * This code was generated by Builder.io.
 */
import Image from "next/image";
import React from "react";

const WeeklyActivity: React.FC = () => {
  return (
    <section className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow mt-1.5 max-md:mt-9">
        <div className="self-end text-lg font-semibold text-right text-slate-700 max-md:mr-2">
          See All
        </div>
        <div className="flex flex-col pt-6 mt-5 w-full bg-white rounded-3xl border border-solid shadow-2xl border-slate-200">
          <div className="flex gap-5 justify-between self-center max-w-full w-[300px]">
            <div className="flex flex-col text-xs text-slate-400">
              <div className="self-start">Balance</div>
              <div className="self-start text-xl font-semibold text-slate-700">
                $5,756
              </div>
              <div className="mt-7 max-md:mr-1.5">CARD HOLDER</div>
              <div className="text-base font-semibold text-slate-700">
                Eddy Cusuma
              </div>
            </div>
            <div className="flex flex-col items-start">
              <Image
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/b47356dea137dd67377eb60e8f583807cbc22ea27a613de93a792a534a449dd4?apiKey=65c59f804f0842d29a4e67cb1a2841cf&"
                alt=""
                width={35}
                height={35}
                className="object-contain self-end aspect-square w-[35px]"
              />
              <div className="mt-8 text-xs text-slate-400">VALID THRU</div>
              <div className="text-base font-semibold text-slate-700">
                12/22
              </div>
            </div>
          </div>
          <div className="flex gap-5 justify-between px-8 py-5 mt-10 rounded-none border border-solid border-slate-200 max-md:px-5">
            <div className="my-auto text-2xl font-semibold text-slate-700">
              3778 **** **** 1234
            </div>
            <div className="flex flex-col items-center px-1.5 rounded-full bg-slate-400 bg-opacity-50 h-[30px] w-[30px]">
              <div className="flex shrink-0 rounded-full bg-slate-400 bg-opacity-50 h-[30px] w-[30px] max-md:-mr-3.5" />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default WeeklyActivity;
